title: CyberBlog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: Toledo7081
  github:  Toledo708

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 5065
google_analytics: G-8JDX8X9XM0
